# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('country', models.CharField(default='None', max_length=100)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('code', models.CharField(default='None', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(default='None', max_length=150)),
                ('code', models.CharField(default='None', max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladmap.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladmap.Boundary')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(default='None', max_length=150)),
                ('code', models.CharField(default='None', max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladmap.Country')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gladmap.State'),
        ),
    ]
