# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gladmap', '0001_initial'),
    ]

    operations = []

