---
pipeline:
  build:
    image: python:${PYTHON_VERSION}
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200/
    commands:
      - pip install -r requirements-ci.txt
      - python manage.py test
    when:
      event: [push, tag]
  build-docker-image:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/toladata/tolaactivity
    file: Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      branches: [master, dev-v2]
      status: [success]

  trigger-deployment:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    verbose: true
    drone_server: http://drone.tola.io
    drone_token: $DRONE_TOKEN
    secrets: [DRONE_TOKEN]
    repo: toladata/deployment
    branch: master
    deploy_to: marathon
    params: "APP_ID=/tolaactivity,APP_GROUP=toladata,APP_NAME=TolaActivity,APP_BRANCH=${DRONE_COMMIT_BRANCH},APP_COMMIT=${DRONE_COMMIT_SHA},APP_TAG=${DRONE_TAG},APP_IMAGE=registry.tola.io/toladata/tolaactivity:${DRONE_COMMIT_SHA}"
    when:
      event: [push, tag]
      branches: [master, dev-v2]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      status: [failure]
      event: [push, tag]
      branches: [master, dev-v2]

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-alpha2

matrix:
  PYTHON_VERSION:
    - 2.7
