---
pipeline:
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install -r requirements/ci.txt
      - python manage.py test
    when:
      event: [push, tag]
    environment:
      - TOLA_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - TOLA_DB_NAME=tola_activity
      - TOLA_DB_USER=root
      - TOLA_DB_PASS=root
      - TOLA_DB_HOST=postgres
      - TOLA_TRACK_SYNC_ENABLED=False
      - DEFAULT_ORG=TolaData

  bandit:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install bandit
      - bandit -x tests/ -r -lll .
    when:
      event: [push, tag]


  build-docker-image:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/toladata/tolaactivity
    file: Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      branch: [master, demo, staging]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      event: [push, tag]
      branch: [master, demo, staging]
      status: [failure]

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=tola_activity
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

matrix:
  PYTHON_VERSION:
    - 2.7
