---
pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install -r requirements-ci.txt
      - python manage.py test
    when:
      event: [push, tag]
    environment:
      - TOLA_DB_ENGINE=django.db.backends.postgresql_psycopg2
      - TOLA_DB_NAME=tola_activity
      - TOLA_DB_USER=root
      - TOLA_DB_PASS=root
      - TOLA_DB_HOST=postgres
      - DEFAULT_ORG=TolaData
  build-docker-image:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/toladata/tolaactivity
    file: Dockerfile
    tags:
      - ${DRONE_COMMIT_SHA}
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      branches: [master, dev-v2]
      status: [success]

  trigger-deployment:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    verbose: true
    drone_server: http://drone.tola.io
    drone_token: $DRONE_TOKEN
    secrets: [DRONE_TOKEN]
    repo: toladata/deployment
    branch: master
    deploy_to: marathon
    params: "APP_ID=/tolaactivity,APP_GROUP=toladata,APP_NAME=TolaActivity,APP_BRANCH=${DRONE_COMMIT_BRANCH},APP_COMMIT=${DRONE_COMMIT_SHA},APP_TAG=${DRONE_TAG},APP_IMAGE=registry.tola.io/toladata/tolaactivity:${DRONE_COMMIT_SHA}"
    when:
      event: [push, tag]
      branches: [master, dev-v2]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      status: [failure]
      event: [push, tag]
      branches: [master, dev-v2]

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=tola_activity
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

matrix:
  PYTHON_VERSION:
    - 2.7
