# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
