# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0002_loggeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='email',
            field=models.CharField(default='user@mercycorps.com', max_length=100),
        ),
    ]
