# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0002_auto_20160418_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='project_type_other',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='project_type_other',
        ),
        migrations.AlterField(
            model_name='customdashboard',
            name='dashboard_description',
            field=models.TextField(blank=True, help_text='What does this custom dashboard display to the user?', null=True, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fund Code'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='activity_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fund Code'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='lin_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LIN Code'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fund Code'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='activity_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='activitydb.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='project_type',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.ProjectType', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fund Code'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='lin_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LIN Code'),
        ),
        migrations.DeleteModel(
            name='ProjectTypeOther',
        ),
    ]
