# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0003_auto_20160428_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergemap',
            name='project_agreement',
        ),
        migrations.RemoveField(
            model_name='mergemap',
            name='project_completion',
        ),
        migrations.RemoveField(
            model_name='programdashboard',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programdashboard',
            name='project_agreement',
        ),
        migrations.RemoveField(
            model_name='programdashboard',
            name='project_completion',
        ),
        migrations.AlterModelOptions(
            name='adminlevelthree',
            options={'ordering': ('name',), 'verbose_name': 'Admin Level 3', 'verbose_name_plural': 'Admin Level 3'},
        ),
        migrations.AlterModelOptions(
            name='approvalauthority',
            options={'ordering': ('approval_user',), 'verbose_name_plural': 'Tola Approval Authority'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'Admin Level 2', 'verbose_name_plural': 'Admin Level 2'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('name',), 'verbose_name': 'Admin Level 1', 'verbose_name_plural': 'Admin Level 1'},
        ),
        migrations.AlterModelOptions(
            name='tolasites',
            options={'verbose_name_plural': 'Tola Sites'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ('name',), 'verbose_name': 'Admin Level 4', 'verbose_name_plural': 'Admin Level 4'},
        ),
        migrations.DeleteModel(
            name='MergeMap',
        ),
        migrations.DeleteModel(
            name='ProgramDashboard',
        ),
    ]
