# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0004_auto_20160521_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='gaitid',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ID'),
        ),
    ]
