# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0004_auto_20160521_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormGuidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, max_length=135, null=True)),
                ('guidance_link', models.URLField(blank=True, null=True)),
                ('guidance', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
        migrations.AlterField(
            model_name='adminlevelthree',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitydb.District', verbose_name='Admin Level 2'),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitydb.Province', verbose_name='Admin Level 1'),
        ),
        migrations.AlterField(
            model_name='office',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitydb.Province', verbose_name='Admin Level 1'),
        ),
        migrations.AlterField(
            model_name='program',
            name='gaitid',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='village',
            name='admin_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.AdminLevelThree', verbose_name='Admin Level 3'),
        ),
    ]
