# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0005_auto_20160521_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlevelthree',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitydb.District', verbose_name='Admin Level 2'),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitydb.Province', verbose_name='Admin Level 1'),
        ),
        migrations.AlterField(
            model_name='village',
            name='admin_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.AdminLevelThree', verbose_name='Admin Level 3'),
        ),
    ]
