# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0008_auto_20160627_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdashboard',
            name='dashboard_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.DashboardTheme'),
        ),
    ]
