# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0008_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='activity_code',
            new_name='initiation',
        ),
    ]
