# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0009_auto_20160627_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdashboard',
            name='dashboard_components',
            field=models.ManyToManyField(blank=True, null=True, to='activitydb.DashboardComponent'),
        ),
    ]
