# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0010_auto_20160621_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='detailed',
            field=models.BooleanField(default=False, verbose_name='Detailed form view'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_agreement', to='activitydb.TolaUser', verbose_name='Send for approval'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='detailed',
            field=models.BooleanField(default=False, verbose_name='Detailed form view'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewing', to='activitydb.TolaUser', verbose_name='Send for review'),
        ),
    ]
