# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0010_auto_20160627_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdashboard',
            name='layout_dictionary',
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='layout_dictionary',
            field=models.TextField(blank=True, null=True, verbose_name='Dashboard Layout Dictionary'),
        ),
    ]
