# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0011_auto_20160628_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='dashboard_name',
        ),
        migrations.RemoveField(
            model_name='historicalprojectcomplete',
            name='dashboard_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='dashboard_name',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='dashboard_name',
        ),
        migrations.RemoveField(
            model_name='projectcomplete',
            name='dashboard_name',
        ),
        migrations.AddField(
            model_name='customdashboard',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_program', to='activitydb.Program', verbose_name='Program'),
        ),
    ]
