# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0011_auto_20160630_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectagreement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_agreement', to='activitydb.TolaUser', verbose_name='Request approval'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewing', to='activitydb.TolaUser', verbose_name='Request review'),
        ),
    ]
