# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0012_auto_20160705_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='zoom',
            field=models.IntegerField(default=5, verbose_name='Zoom'),
        ),
    ]
