# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0012_auto_20160629_1522'),
        ('activitydb', '0013_country_zoom'),
    ]

    operations = [
    ]
