# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0013_country_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='distribution',
            field=models.ManyToManyField(blank=True, to='activitydb.Distribution'),
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='training',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='training',
            field=models.ManyToManyField(blank=True, to='activitydb.TrainingAttendance'),
        ),
    ]
