# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0014_auto_20160715_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteprofile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Site Active'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Site Active'),
        ),
    ]
