# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentdatasource',
            name='data_source_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data Source Type'),
        ),
        migrations.AlterField(
            model_name='componentdatasource',
            name='data_filter_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Key Term'),
        ),
    ]
