# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0015_auto_20160718_0856'),
        ('activitydb', '0015_auto_20160715_1132'),
    ]

    operations = [
    ]
