# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0015_auto_20160715_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitydb.Program'),
        ),
    ]
