# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0016_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentdatasource',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='customdashboard',
            name='component_map',
            field=models.TextField(blank=True, null=True, verbose_name='Dashboard Layout Dictionary'),
        ),
        migrations.AddField(
            model_name='program',
            name='dashboard_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboard', to='activitydb.CustomDashboard'),
        ),
        migrations.AlterField(
            model_name='customdashboard',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, related_name='componentset', to='activitydb.DashboardComponent'),
        ),
        migrations.AlterField(
            model_name='dashboardcomponent',
            name='data_sources',
            field=models.ManyToManyField(related_name='datasourceset', to='activitydb.ComponentDataSource'),
        ),
    ]
