# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0017_auto_20160728_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojectagreement',
            name='detailed',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='detailed',
        ),
        migrations.AddField(
            model_name='historicalprojectagreement',
            name='short',
            field=models.BooleanField(default=True, verbose_name='Short Form (recommended)'),
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='short',
            field=models.BooleanField(default=True, verbose_name='Short Form (recommended)'),
        ),
    ]
