# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0017_auto_20160804_1005'),
        ('activitydb', '0017_auto_20160728_1533'),
    ]

    operations = [
    ]
