# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0018_auto_20160807_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomplete',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, to='activitydb.Stakeholder'),
        ),
    ]
