# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-15 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0019_projectcomplete_stakeholder'),
        ('activitydb', '0018_merge'),
    ]

    operations = [
    ]
