# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0020_auto_20160817_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual Value'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual Value'),
        ),
    ]
