# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0021_auto_20160822_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='program',
            field=models.ManyToManyField(blank=True, to='activitydb.Program'),
        ),
    ]
