# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0022_beneficiary_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolasites',
            name='tola_report_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
