# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0023_tolasites_tola_report_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('email', models.CharField(default='user@mercycorps.com', max_length=100)),
            ],
        ),
    ]
