# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0024_loggeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.TolaUser'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Value'),
        ),
    ]
