# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0025_auto_20160825_1105'),
        ('activitydb', '0020_merge'),
    ]

    operations = [
    ]
