# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0026_auto_20160907_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectcomplete',
            name='short',
            field=models.BooleanField(default=True, verbose_name='Short Form (recommended)'),
        ),
        migrations.AddField(
            model_name='projectcomplete',
            name='short',
            field=models.BooleanField(default=True, verbose_name='Short Form (recommended)'),
        ),
    ]
