# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0027_auto_20161010_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectagreement',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, to='activitydb.Stakeholder', verbose_name='Stakeholders'),
        ),
    ]
