# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0026_merge'),
        ('activitydb', '0027_auto_20161010_2128'),
        ('activitydb', '0026_auto_20160906_2345'),
    ]

    operations = [
    ]
