# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0028_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdashboard',
            name='components',
        ),
        migrations.RemoveField(
            model_name='customdashboard',
            name='program',
        ),
        migrations.RemoveField(
            model_name='customdashboard',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='dashboardcomponent',
            name='data_sources',
        ),
        migrations.RemoveField(
            model_name='program',
            name='dashboard_name',
        ),
        migrations.DeleteModel(
            name='ComponentDataSource',
        ),
        migrations.DeleteModel(
            name='CustomDashboard',
        ),
        migrations.DeleteModel(
            name='DashboardComponent',
        ),
        migrations.DeleteModel(
            name='DashboardTheme',
        ),
    ]
