# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-02 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0028_auto_20161024_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='TolaUserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Report Tola User',
                'proxy': True,
                'verbose_name_plural': 'Report Tola Users',
            },
            bases=('activitydb.tolauser',),
        ),
    ]
