# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0072_auto_20160315_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalauthority',
            name='fund',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fund'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='cfw_estimate_cost_materials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimated Total Cost of Materials'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='cfw_estimate_wages_budgeted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimated Wages Budgeted'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='distribution_estimate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimated # of Items Distributed'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='distribution_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Items Distributed'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='distribution_uom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='cfw_estimate_cost_materials',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimated Total Cost of Materials'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='cfw_estimate_wages_budgeted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimated Wages Budgeted'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='distribution_estimate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimated # of Items Distributed'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='distribution_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type of Items Distributed'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='distribution_uom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='agency_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
