# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0074_auto_20160331_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchmarks',
            options={'ordering': ('description',), 'verbose_name_plural': 'Project Components'},
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated Budget'),
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual Cost'),
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='est_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='est_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benchmarks',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.SiteProfile'),
        ),
    ]
