# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0075_auto_20160406_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolauser',
            old_name='created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='tolauser',
            old_name='updated',
            new_name='edit_date',
        ),
    ]
