# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 09:18
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'Achieved')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Remarks/comments')),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name=b'Comment/Explanation')),
                ('update_count_tola_table', models.BooleanField(default=False, verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_agreement2', to='workflow.WorkflowLevel2', verbose_name=b'Project Initiation')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_data', to='workflow.TolaUser', verbose_name=b'Originated By')),
                ('complete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_complete2', to='workflow.WorkflowLevel2')),
            ],
            options={
                'ordering': ('agreement', 'indicator', 'date_collected', 'create_date'),
                'verbose_name_plural': 'Indicator Output/Outcome Collected Data',
            },
        ),
        migrations.CreateModel(
            name='DataCollectionFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=135, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('numdays', models.PositiveIntegerField(default=0, verbose_name=b'Frequency in number of days')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisaggregationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=765)),
                ('customsort', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisaggregationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaggregation_type', models.CharField(blank=True, max_length=135)),
                ('description', models.CharField(blank=True, max_length=765)),
                ('standard', models.BooleanField(default=False, verbose_name=b'Standard (TolaData Admins Only)')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country')),
            ],
        ),
        migrations.CreateModel(
            name='DisaggregationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('disaggregation_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationLabel')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=765)),
                ('feed_url', models.CharField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalServiceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(blank=True, max_length=765)),
                ('record_id', models.CharField(blank=True, max_length=765, verbose_name=b'Unique ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('external_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.ExternalService')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCollectedData',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('achieved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'Achieved')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Remarks/comments')),
                ('date_collected', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name=b'Comment/Explanation')),
                ('update_count_tola_table', models.BooleanField(default=False, verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.WorkflowLevel2')),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser')),
                ('complete', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.WorkflowLevel2')),
                ('evidence', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Documentation')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical collected data',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Rationale or Justification for Indicator')),
                ('unit_of_measure', models.CharField(blank=True, max_length=135, null=True, verbose_name=b'Unit of Measure')),
                ('baseline', models.CharField(blank=True, max_length=255, null=True)),
                ('lop_target', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'LOP Target')),
                ('rationale_for_target', models.TextField(blank=True, max_length=255, null=True)),
                ('means_of_verification', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Means of Verification / Data Source')),
                ('data_collection_method', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Data Collection Method')),
                ('data_points', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Data Points')),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Responsible Person(s) and Team')),
                ('method_of_analysis', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Method of Analysis')),
                ('information_use', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Information Use')),
                ('quality_assurance', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Quality Assurance Measures')),
                ('data_issues', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Data Issues')),
                ('indicator_changes', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Changes to Indicator')),
                ('comments', models.TextField(blank=True, max_length=255, null=True)),
                ('key_performance_indicator', models.BooleanField(default=False, verbose_name=b'Key Performance Indicator?')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approval_submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser')),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.TolaUser')),
                ('data_collection_frequency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.DataCollectionFrequency')),
                ('external_service_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ExternalServiceRecord')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical indicator',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Rationale or Justification for Indicator')),
                ('unit_of_measure', models.CharField(blank=True, max_length=135, null=True, verbose_name=b'Unit of Measure')),
                ('baseline', models.CharField(blank=True, max_length=255, null=True)),
                ('lop_target', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'LOP Target')),
                ('rationale_for_target', models.TextField(blank=True, max_length=255, null=True)),
                ('means_of_verification', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Means of Verification / Data Source')),
                ('data_collection_method', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Data Collection Method')),
                ('data_points', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Data Points')),
                ('responsible_person', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Responsible Person(s) and Team')),
                ('method_of_analysis', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Method of Analysis')),
                ('information_use', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Information Use')),
                ('quality_assurance', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Quality Assurance Measures')),
                ('data_issues', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Data Issues')),
                ('indicator_changes', models.TextField(blank=True, max_length=500, null=True, verbose_name=b'Changes to Indicator')),
                ('comments', models.TextField(blank=True, max_length=255, null=True)),
                ('key_performance_indicator', models.BooleanField(default=False, verbose_name=b'Key Performance Indicator?')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('approval_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_submitted_by', to='workflow.TolaUser')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_indicator', to='workflow.TolaUser')),
                ('data_collection_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.DataCollectionFrequency', verbose_name=b'Frequency of Data Collection')),
                ('disaggregation', models.ManyToManyField(blank=True, to='indicators.DisaggregationType')),
                ('external_service_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.ExternalServiceRecord', verbose_name=b'External Service ID')),
            ],
            options={
                'ordering': ('create_date',),
                'permissions': (('view_indicator', 'View Indicator Model'),),
            },
        ),
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(blank=True, max_length=135)),
                ('description', models.TextField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135)),
                ('description', models.TextField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135)),
                ('description', models.TextField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('workflowlevel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1')),
            ],
            options={
                'ordering': ('workflowlevel1', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PeriodicTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('customsort', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=135)),
                ('description', models.CharField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.ReportingFrequency')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135)),
                ('description', models.TextField(blank=True, max_length=765)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country')),
            ],
            options={
                'ordering': ('country', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TolaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('table_id', models.IntegerField(blank=True, null=True)),
                ('remote_owner', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('unique_count', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.ManyToManyField(blank=True, to='workflow.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.ManyToManyField(blank=True, to='indicators.IndicatorType'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='level',
            field=models.ManyToManyField(blank=True, to='indicators.Level'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='obj_indicator', to='indicators.Objective', verbose_name=b'Objective'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.ReportingFrequency', verbose_name=b'Frequency of Reporting'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Sector'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='strategic_objectives',
            field=models.ManyToManyField(blank=True, related_name='strat_indicator', to='indicators.StrategicObjective', verbose_name=b'Country Strategic Objective'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='workflowlevel1',
            field=models.ManyToManyField(to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ReportingFrequency'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Sector'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='indicator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.Indicator'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.PeriodicTarget'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.TolaTable'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='disaggregationlabel',
            name='disaggregation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationType'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, to='indicators.DisaggregationValue'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Documentation', verbose_name=b'Evidence Document or Link'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.PeriodicTarget'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='site',
            field=models.ManyToManyField(blank=True, to='workflow.SiteProfile'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.TolaTable'),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_workflowlevel1', to='workflow.WorkflowLevel1'),
        ),
    ]
