# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolatable',
            name='unique_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
