# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, verbose_name=b'Would you like to update the achieved total with the count from TolaTables?'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, verbose_name=b'Would you like to update the achieved total with the count from TolaTables?'),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='unique_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
