# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20170105_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_program', to='workflow.WorkflowLevel1'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.WorkflowLevel1'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
    ]
