# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20170707_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='indicator_uuid',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=255, verbose_name=b'Indicator UUID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'Indicator UUID'),
        ),
    ]
