# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20170522_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('create_date',), 'permissions': (('view_indicator', 'View Indicator Model'),)},
        ),
    ]
