# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_tolatable_unique_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False),
        ),
    ]
