# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20160502_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='q_agreement2', to='activitydb.ProjectAgreement', verbose_name=b'Project Initiation'),
        ),
    ]
