# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20170515_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('level1', 'name')},
        ),
        migrations.RenameField(
            model_name='collecteddata',
            old_name='program',
            new_name='level1',
        ),
        migrations.RenameField(
            model_name='historicalcollecteddata',
            old_name='program',
            new_name='level1',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='program',
            new_name='level1',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='program',
            new_name='level1',
        ),
    ]
