# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20171101_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collecteddata',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='historicalcollecteddata',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='historicalindicator',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='owner',
            new_name='created_by',
        ),
    ]
