# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170517_0828'),
        ('indicators', '0003_auto_20170517_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('workflowlevel1', 'name')},
        ),
        migrations.RenameField(
            model_name='historicalcollecteddata',
            old_name='level1',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='level1',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='level1',
            new_name='workflowlevel1',
        ),
        migrations.RemoveField(
            model_name='collecteddata',
            name='level1',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_workflowlevel1', to='workflow.WorkflowLevel1'),
        ),
    ]
