# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20170729_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='data_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'Data UUID'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='data_uuid',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=255, verbose_name=b'Data UUID'),
        ),
    ]
