# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20160613_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?'),
        ),
    ]
