# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 06:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20171101_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'LOP Target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name=b'LOP Target'),
        ),
    ]
