# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 12:10
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20180204_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text=b'Actual or total for this record', max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b'Who approved collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_data', to='workflow.TolaUser', verbose_name=b'Approved By'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='data_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text=b'', max_length=255, unique=True, verbose_name=b'Data UUID'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=b'HOw was this data collected', null=True, verbose_name=b'Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, help_text=b'Values for each disaggregated field', to='indicators.DisaggregationValue'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text=b'Evidence Document or Link', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Documentation', verbose_name=b'Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='indicator',
            field=models.ForeignKey(help_text=b'Related indicator for this data', on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=b'Releate this collection to a periodic target', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.PeriodicTarget'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='site',
            field=models.ManyToManyField(blank=True, help_text=b'Geographic location for data source', to='workflow.SiteProfile'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, help_text=b'If Track table was used link to it here', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.TolaTable'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=b'Update the unique count from Table if linked when updated', verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, help_text=b'Related workflowlevel1 if no workflowlevel 2 for this data and no indicator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_workflowlevel1', to='workflow.WorkflowLevel1'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, help_text=b'Related workflowlevel1 for this data if no indicator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_workflowlevel2', to='workflow.WorkflowLevel2', verbose_name=b'Project Initiation'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='disaggregation_type',
            field=models.CharField(blank=True, help_text=b'Data disaggregation by age,gender,location etc.', max_length=135),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='name',
            field=models.CharField(blank=True, help_text=b'External Indicator service for template of an Indicator instance', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text=b'Actual or total for this record', max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='data_uuid',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, help_text=b'', max_length=255, verbose_name=b'Data UUID'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=b'HOw was this data collected', null=True, verbose_name=b'Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=b'Update the unique count from Table if linked when updated', verbose_name=b'Would you like to update the achieved total with the row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=b'Initial set of data used for comparison or a control', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='comments',
            field=models.TextField(blank=True, help_text=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=b'How was the data collected', max_length=255, null=True, verbose_name=b'Data Collection Method'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=b'Problems with the data quality if any', max_length=500, null=True, verbose_name=b'Data Issues'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=b'', max_length=500, null=True, verbose_name=b'Data Points'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='definition',
            field=models.TextField(blank=True, help_text=b'Descriptive text for broader definiton and goal', null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=b'How did the indicator change over time if at all', max_length=500, null=True, verbose_name=b'Changes to Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=b'Information Use', max_length=255, null=True, verbose_name=b'Information Use'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='justification',
            field=models.TextField(blank=True, help_text=b'Rationale or Justification for Indicator', max_length=500, null=True, verbose_name=b'Rationale or Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='key_performance_indicator',
            field=models.BooleanField(default=False, help_text=b'Yes/No is this a key measurement for the overall effort', verbose_name=b'Key Performance Indicator?'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text=b'Life of Program or Project goal for actual', max_digits=20, verbose_name=b'LOP Target'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=b'Means of Verification / Data Source', max_length=255, null=True, verbose_name=b'Means of Verification / Data Source'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=b'Method of Analysis', max_length=255, null=True, verbose_name=b'Method of Analysis'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='notes',
            field=models.TextField(blank=True, help_text=b'', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='number',
            field=models.CharField(blank=True, help_text=b'Internal organizational structure for relating to indicator and level', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=b'Quality Assurance Measures', max_length=500, null=True, verbose_name=b'Quality Assurance Measures'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=b'Reasoning for why the target value was set', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=b'Responsible Person(s) and Team', max_length=255, null=True, verbose_name=b'Responsible Person(s) and Team'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='source',
            field=models.CharField(blank=True, help_text=b'Origin of indicator', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=b'How will progress be measured', max_length=135, null=True, verbose_name=b'Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, help_text=b'Who requested approval of the indicator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_submitted_by', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b'Who approved the indicator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_indicator', to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=b'Initial set of data used for comparison or a control', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='comments',
            field=models.TextField(blank=True, help_text=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, help_text=b'How often was the data collected', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_collection_frequency', to='indicators.Frequency', verbose_name=b'Frequency of Data Collection'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_method',
            field=models.CharField(blank=True, help_text=b'How was the data collected', max_length=255, null=True, verbose_name=b'Data Collection Method'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=b'Problems with the data quality if any', max_length=500, null=True, verbose_name=b'Data Issues'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=b'', max_length=500, null=True, verbose_name=b'Data Points'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='definition',
            field=models.TextField(blank=True, help_text=b'Descriptive text for broader definiton and goal', null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='disaggregation',
            field=models.ManyToManyField(blank=True, help_text=b'Predefined units to split total actauls', to='indicators.DisaggregationType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b'', null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='external_service_record',
            field=models.ForeignKey(blank=True, help_text=b'What third party indicator service was this pulled from if any', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.ExternalServiceRecord', verbose_name=b'External Service ID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_changes',
            field=models.TextField(blank=True, help_text=b'How did the indicator change over time if at all', max_length=500, null=True, verbose_name=b'Changes to Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.ManyToManyField(blank=True, help_text=b'If indicator was pulled from aservie select one here', to='indicators.IndicatorType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='information_use',
            field=models.CharField(blank=True, help_text=b'Information Use', max_length=255, null=True, verbose_name=b'Information Use'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='justification',
            field=models.TextField(blank=True, help_text=b'Rationale or Justification for Indicator', max_length=500, null=True, verbose_name=b'Rationale or Justification for Indicator'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='key_performance_indicator',
            field=models.BooleanField(default=False, help_text=b'Yes/No is this a key measurement for the overall effort', verbose_name=b'Key Performance Indicator?'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.ForeignKey(blank=True, help_text=b'The results framework level goal, objective etc. for this indicator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Level'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text=b'Life of Program or Project goal for actual', max_digits=20, verbose_name=b'LOP Target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='means_of_verification',
            field=models.CharField(blank=True, help_text=b'Means of Verification / Data Source', max_length=255, null=True, verbose_name=b'Means of Verification / Data Source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='method_of_analysis',
            field=models.CharField(blank=True, help_text=b'Method of Analysis', max_length=255, null=True, verbose_name=b'Method of Analysis'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='notes',
            field=models.TextField(blank=True, help_text=b'', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='number',
            field=models.CharField(blank=True, help_text=b'Internal organizational structure for relating to indicator and level', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='objectives',
            field=models.ManyToManyField(blank=True, help_text=b'Internal stated objective', related_name='obj_indicator', to='indicators.Objective', verbose_name=b'Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='quality_assurance',
            field=models.TextField(blank=True, help_text=b'Quality Assurance Measures', max_length=500, null=True, verbose_name=b'Quality Assurance Measures'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=b'Reasoning for why the target value was set', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, help_text=b'Frequency of Reporting', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.Frequency', verbose_name=b'Frequency of Reporting'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='responsible_person',
            field=models.CharField(blank=True, help_text=b'Responsible Person(s) and Team', max_length=255, null=True, verbose_name=b'Responsible Person(s) and Team'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, help_text=b'Primary related sector or type of work done', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, help_text=b'Origin of indicator', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='strategic_objectives',
            field=models.ManyToManyField(blank=True, help_text=b'Organizational objectives', related_name='strat_indicator', to='indicators.StrategicObjective', verbose_name=b'Country Strategic Objective'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, help_text=b'Additiona related sectors or type of work if any', related_name='indicator_sub_sector', to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=b'How will progress be measured', max_length=135, null=True, verbose_name=b'Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='workflowlevel1',
            field=models.ManyToManyField(help_text=b'Related workflowlevel1 or project/prgoram etc.', to='workflow.WorkflowLevel1'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, help_text=b'Results framework or general indicator collection or label for level', max_length=135),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.CharField(blank=True, help_text=b'Objective for workflowleve1 to associate with indicator', max_length=135),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='name',
            field=models.CharField(blank=True, help_text=b'Organizational objective to associate with inidicator', max_length=135),
        ),
    ]
