# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20170626_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalservice',
            old_name='url',
            new_name='service_url',
        ),
    ]
