# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20160630_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindicator',
            name='country',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='country',
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='standard',
            field=models.BooleanField(default=False, verbose_name=b'Standard (TolaData Admins Only)'),
        ),
    ]
