# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_auto_20170804_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'LOP Target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'LOP Target'),
        ),
    ]
