# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20180211_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=b'How was this data collected', null=True, verbose_name=b'Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=b'Relate this collection to a periodic target', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.PeriodicTarget'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='description',
            field=models.TextField(blank=True, help_text=b'How was this data collected', null=True, verbose_name=b'Remarks/comments'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.ManyToManyField(blank=True, help_text=b'If indicator was pulled from a service select one here', to='indicators.IndicatorType'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='workflowlevel1',
            field=models.ManyToManyField(help_text=b'Related workflowlevel1 or project/program etc.', to='workflow.WorkflowLevel1'),
        ),
    ]
