# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20160705_1028'),
        ('indicators', '0004_auto_20160628_1600'),
    ]

    operations = [
    ]
