# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 20:46
from __future__ import unicode_literals

from django.utils import timezone

from django.db import migrations

def moveTargetedToPeriodicTargets(apps, schema_editor):
    CollectedData = apps.get_model("indicators", "CollectedData")
    PeriodicTarget = apps.get_model("indicators", "PeriodicTarget")

    collecteddata = CollectedData.objects.all().order_by('indicator')
    counter = 1
    prev_indicator = 0
    for data in collecteddata:
        if prev_indicator != data.indicator.pk:
            prev_indicator = data.indicator.pk
            counter = 1
        pt = PeriodicTarget.objects.create(period="Temp %s" % counter,
                                      target=data.targeted,
                                      indicator=data.indicator,
                                      create_date=timezone.now())
        data.periodic_target = pt
        data.save()
        counter += 1


# https://github.com/toladata/TolaActivity/blob/new_dev/workflow/migrations/0013_auto_20170406_1012.py
class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20170509_1341'),
    ]

    operations = [
        migrations.RunPython(moveTargetedToPeriodicTargets),
    ]
