# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20170630_0004'),
        ('indicators', '0005_auto_20170628_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ('workflowlevel2', 'indicator', 'date_collected', 'create_date'), 'verbose_name_plural': 'Indicator Output/Outcome Collected Data'},
        ),
        migrations.RenameField(
            model_name='historicalcollecteddata',
            old_name='agreement',
            new_name='workflowlevel2',
        ),
        migrations.RemoveField(
            model_name='collecteddata',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='collecteddata',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='historicalcollecteddata',
            name='complete',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_workflowlevel2', to='workflow.WorkflowLevel2', verbose_name=b'Project Initiation'),
        ),
    ]
