# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20170817_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='color',
            field=models.CharField(blank=True, max_length=135),
        ),
    ]
