# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20180226_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaggregationtype',
            name='default_global',
        ),
        migrations.RemoveField(
            model_name='disaggregationtype',
            name='standard',
        ),
        migrations.AddField(
            model_name='disaggregationtype',
            name='availability',
            field=models.CharField(blank=True, choices=[(b'org', b'Organization Level'), (b'wfl1', b'Only for this WFL1')], max_length=5, null=True),
        ),
    ]
