# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20170630_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='data_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name=b'Data UUID'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='data_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name=b'Data UUID'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='indicator_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name=b'Indicator UUID'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name=b'Indicator UUID'),
        ),
    ]
