# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-29 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_auto_20160826_0620'),
        ('indicators', '0006_merge'),
    ]

    operations = [
    ]
