# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_level_color'),
    ]

    operations = [
    ]
