# -*- coding: utf-8 -*-
# Generated by Django A.B on YYYY-MM-DD HH:MM
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    for row in Indicator.objects.all():
        row.indicator_key = uuid.uuid4()
        row.save(update_fields=['indicator_uuid'])

    CollectedData = apps.get_model('indicators', 'CollectedData')
    for row in CollectedData.objects.all():
        row.data_key = uuid.uuid4()
        row.save(update_fields=['data_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20170706_0153'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]