# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_auto_20180423_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationvalue',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
    ]
