# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20170701_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='data_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'Data UUID'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='data_uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255, verbose_name=b'Data UUID'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='indicator_uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255, verbose_name=b'Indicator UUID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name=b'Indicator UUID'),
        ),
    ]
