# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20180509_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='actual_formula',
            field=models.CharField(blank=True, choices=[(b'average', b'Average'), (b'user_defined', b'User defined')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[(b'numeric', b'Numeric'), (b'percentage', b'Percentage')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='direction',
            field=models.CharField(blank=True, choices=[(b'increasing', b'Increasing'), (b'decreasing', b'Decreasing')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='actual_formula',
            field=models.CharField(blank=True, choices=[(b'average', b'Average'), (b'user_defined', b'User defined')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='calculation_type',
            field=models.CharField(blank=True, choices=[(b'numeric', b'Numeric'), (b'percentage', b'Percentage')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='direction',
            field=models.CharField(blank=True, choices=[(b'increasing', b'Increasing'), (b'decreasing', b'Decreasing')], max_length=15, null=True),
        ),
    ]
