# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20170829_0745'),
        ('indicators', '0009_auto_20170823_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country'),
        ),
        migrations.AddField(
            model_name='level',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='level',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
