# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_auto_20170904_0443'),
        ('indicators', '0010_auto_20170830_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, related_name='indicator_sub_sector', to='workflow.Sector'),
        ),
    ]
