# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_auto_20180607_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='total_actual',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.CollectedData'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='total_actual',
            field=models.ForeignKey(blank=True, help_text=b'The collected data selected to be used in the actual formula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_total_actual', to='indicators.CollectedData', verbose_name=b'Total Actual'),
        ),
    ]
