# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20180620_0557'),
        ('indicators', '0011_auto_20180613_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingperiod',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='reportingperiod',
            name='organization',
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='period',
            field=models.CharField(blank=True, help_text=b'Predefined reporting period for a workflowlevel1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, help_text=b'Related workflowlevel1 or project/program etc.', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
    ]
