# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_auto_20171204_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='target_frequency',
            field=models.IntegerField(choices=[(1, b'Life of Program (LoP) only'), (2, b'Midline and endline'), (3, b'Annual'), (4, b'Semi-annual'), (5, b'Tri-annual'), (6, b'Quarterly'), (7, b'Monthly'), (8, b'Event')], null=True, verbose_name=b'Target frequency'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='target_frequency_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'First event name*'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='target_frequency_num_periods',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Number of target periods*'),
        ),
        migrations.AddField(
            model_name='historicalindicator',
            name='target_frequency_start',
            field=models.DateField(blank=True, null=True, verbose_name=b'First target period begins*'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_frequency',
            field=models.IntegerField(choices=[(1, b'Life of Program (LoP) only'), (2, b'Midline and endline'), (3, b'Annual'), (4, b'Semi-annual'), (5, b'Tri-annual'), (6, b'Quarterly'), (7, b'Monthly'), (8, b'Event')], null=True, verbose_name=b'Target frequency'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_frequency_custom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'First event name*'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_frequency_num_periods',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Number of target periods*'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_frequency_start',
            field=models.DateField(blank=True, null=True, verbose_name=b'First target period begins*'),
        ),
        migrations.AddField(
            model_name='periodictarget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodictarget',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name=b'Unit of Measure*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name=b'Unit of Measure*'),
        ),
    ]
