# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_indicator_sub_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
