# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-04 09:56
from __future__ import unicode_literals

from django.db import migrations
from ..models import Indicator


def set_calculation_type(apps, schema_editor):
    Indicator.objects.all().update(
        calculation_type=Indicator.CALC_TYPE_NUMERIC)


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_auto_20180704_0256'),
    ]

    operations = [
        migrations.RunPython(set_calculation_type),
    ]
