# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_auto_20170913_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indicators.ReportingFrequency'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_collection_frequency', to='indicators.ReportingFrequency', verbose_name=b'Frequency of Data Collection'),
        ),
    ]
