# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-27 12:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_set_all_calculation_type_to_numeric'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolatable',
            name='formula',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
