# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 12:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_tolatable_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='column_name',
            field=models.CharField(blank=True, help_text=b'Formula', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='formula',
            field=models.CharField(blank=True, help_text=b'Formula', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='table_uuid',
            field=models.CharField(blank=True, help_text=b'Track service table url', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='column_name',
            field=models.CharField(blank=True, help_text=b'Formula', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='formula',
            field=models.CharField(blank=True, help_text=b'Formula', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='table_uuid',
            field=models.CharField(blank=True, help_text=b'Track service table url', max_length=255, null=True),
        ),
    ]
