# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_auto_20170913_0422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportingFrequency',
            new_name='Frequency',
        ),
    ]
