# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_auto_20190116_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='actual_formula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='actual_formula',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
