# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_auto_20180323_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=b' ', verbose_name=b'Would you like to update the achieved total with the         row count from TolaTables?'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='update_count_tola_table',
            field=models.BooleanField(default=False, help_text=b' ', verbose_name=b'Would you like to update the achieved total with the         row count from TolaTables?'),
        ),
    ]
