# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_auto_20170918_0706'),
        ('indicators', '0017_remove_level_workflowlevel1'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
    ]
