# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0017_auto_20190118_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationvalue',
            name='column_name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='disaggregationvalue',
            name='column_value',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='disaggregationvalue',
            name='table_uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
