# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-23 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0017_auto_20180323_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='unit_of_measure_type',
            field=models.IntegerField(choices=[(1, b'Number (#)'), (2, b'Percentage (%)')], default=1, help_text=b' ', null=True, verbose_name=b'Unit Type'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure_type',
            field=models.IntegerField(choices=[(1, b'Number (#)'), (2, b'Percentage (%)')], default=1, help_text=b' ', null=True, verbose_name=b'Unit Type'),
        ),
    ]
