# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_auto_20180323_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='direction_of_change',
            field=models.IntegerField(blank=True, choices=[(1, b'Direction of change (none)'), (2, b'Positive (+)'), (3, b'Negative (-)')], default=1, help_text=b' ', null=True, verbose_name=b'Direction of Chnage'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='direction_of_change',
            field=models.IntegerField(blank=True, choices=[(1, b'Direction of change (none)'), (2, b'Positive (+)'), (3, b'Negative (-)')], default=1, help_text=b' ', null=True, verbose_name=b'Direction of Chnage'),
        ),
    ]
