# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_level_workflowlevel1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Level'),
        ),
    ]
