# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_auto_20190124_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='cell_value',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='cell_value',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
