# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0043_auto_20170918_0725'),
        ('indicators', '0019_auto_20170918_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaggregationtype',
            name='country',
        ),
        migrations.AddField(
            model_name='disaggregationtype',
            name='default_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disaggregationtype',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
