# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0019_auto_20180326_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicator',
            name='is_cumulative',
            field=models.NullBooleanField(help_text=b' ', verbose_name=b'C / NC'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_cumulative',
            field=models.NullBooleanField(help_text=b' ', verbose_name=b'C / NC'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, b'Direction of change (none)'), (2, b'Positive (+)'), (3, b'Negative (-)')], default=1, help_text=b' ', null=True, verbose_name=b'Direction of Chnage'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, b'Direction of change (none)'), (2, b'Positive (+)'), (3, b'Negative (-)')], default=1, help_text=b' ', null=True, verbose_name=b'Direction of Chnage'),
        ),
    ]
