# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-28 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0019_auto_20190125_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='evidence_url',
            field=models.CharField(blank=True, help_text=b'Evidence Document url', max_length=255, null=True, verbose_name=b'Evidence Document url'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='evidence_url',
            field=models.CharField(blank=True, help_text=b'Evidence Document url', max_length=255, null=True, verbose_name=b'Evidence Document url'),
        ),
    ]
