# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_auto_20180326_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ('indicator', 'create_date', 'date_collected'), 'verbose_name_plural': 'Indicator Output/Outcome Collected Data'},
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='cumulative_achieved',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name=b'Cumulative Actuals'),
        ),
        migrations.AddField(
            model_name='historicalcollecteddata',
            name='cumulative_achieved',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name=b'Cumulative Actuals'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=b' ', max_digits=20, verbose_name=b'Actual'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=2, help_text=b' ', max_digits=20, verbose_name=b'Actual'),
        ),
    ]
