# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_auto_20170919_0701'),
        ('indicators', '0020_auto_20170919_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolatable',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='workflowlevel1',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1'),
        ),
    ]
