# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 10:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_auto_20190128_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text=b'Actual or total for this record', max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='achieved',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text=b'Actual or total for this record', max_digits=20, verbose_name=b'Achieved'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='actuals',
            field=models.DecimalField(blank=True, decimal_places=4, help_text=b'Sum of collected datas achieved', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text=b'Life of Program or Project goal for actual', max_digits=20, verbose_name=b'LOP Target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='actuals',
            field=models.DecimalField(blank=True, decimal_places=4, help_text=b'Sum of collected datas achieved', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), help_text=b'Life of Program or Project goal for actual', max_digits=20, verbose_name=b'LOP Target'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='target',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20),
        ),
    ]
