# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_auto_20190220_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='value',
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
    ]
