# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_auto_20170919_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationtype',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
