# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0022_auto_20170923_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolatable',
            name='column_avg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='column_sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='count_column_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='count_column_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='refresh_interval',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='remote_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
