# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-06 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0022_auto_20180402_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolatable',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
