# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0022_auto_20170923_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolatable',
            name='column_avg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='column_sum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='count_column_name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='count_column_name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tolatable',
            name='refresh_interval',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
