# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-07 02:01
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_auto_20180406_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacollectionfrequency',
            options={'verbose_name': 'Data Collection Frequency'},
        ),
        migrations.AlterModelOptions(
            name='externalservice',
            options={'verbose_name': 'External Service'},
        ),
        migrations.AlterModelOptions(
            name='externalservicerecord',
            options={'verbose_name': 'External Service Record'},
        ),
        migrations.AlterModelOptions(
            name='historicalindicator',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicator'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ('create_date',), 'verbose_name': 'Indicator'},
        ),
        migrations.AlterModelOptions(
            name='indicatortype',
            options={'verbose_name': 'Indicator Type'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Level'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('program', 'name'), 'verbose_name': 'Objective'},
        ),
        migrations.AlterModelOptions(
            name='periodictarget',
            options={'ordering': ('customsort', '-create_date'), 'verbose_name': 'Periodic Target'},
        ),
        migrations.AlterModelOptions(
            name='reportingfrequency',
            options={'verbose_name': 'Reporting Frequency'},
        ),
        migrations.AlterModelOptions(
            name='reportingperiod',
            options={'verbose_name': 'Reporting Period'},
        ),
        migrations.AlterModelOptions(
            name='strategicobjective',
            options={'ordering': ('country', 'name'), 'verbose_name': 'Strategic Objectives'},
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='complete',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_complete2', to='workflow.ProjectComplete', verbose_name='Project Complete'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Date collected'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='indicators.DisaggregationValue', verbose_name='Disaggregation Value'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='indicator',
            field=models.ForeignKey(help_text=b' ', on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.PeriodicTarget', verbose_name='Periodic target'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='program',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_program', to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='datacollectionfrequency',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='datacollectionfrequency',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='datacollectionfrequency',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='datacollectionfrequency',
            name='frequency',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='customsort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Customsort'),
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='disaggregation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationType', verbose_name='Disaggregation type'),
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='disaggregationlabel',
            name='label',
            field=models.CharField(blank=True, max_length=765, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name=b'Country'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='description',
            field=models.CharField(blank=True, max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='disaggregation_type',
            field=models.CharField(blank=True, max_length=135, verbose_name='Disaggregation type'),
        ),
        migrations.AlterField(
            model_name='disaggregationtype',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='disaggregation_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationLabel', verbose_name='Disaggregation label'),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='disaggregationvalue',
            name='value',
            field=models.CharField(blank=True, max_length=765, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='feed_url',
            field=models.CharField(blank=True, max_length=765, verbose_name='Feed url'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='url',
            field=models.CharField(blank=True, max_length=765, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='external_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.ExternalService', verbose_name='External service'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='full_url',
            field=models.CharField(blank=True, max_length=765, verbose_name='Full URL'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='date_collected',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Date collected'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='comments',
            field=models.TextField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=b' ', max_length=500, null=True, verbose_name='Data issues'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=b' ', max_length=500, null=True, verbose_name='Data points'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='definition',
            field=models.TextField(blank=True, help_text=b' ', null=True, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, 'Direction of change (not applicable)'), (2, 'Positive (+)'), (3, 'Negative (-)')], default=1, help_text=b' ', null=True, verbose_name='Direction of Change'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='number',
            field=models.CharField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Rationale for target'),
        ),
        migrations.AlterField(
            model_name='historicalindicator',
            name='source',
            field=models.CharField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_submitted_by', to='workflow.TolaUser', verbose_name='Approval submitted by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_indicator', to='workflow.TolaUser', verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='comments',
            field=models.TextField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_issues',
            field=models.TextField(blank=True, help_text=b' ', max_length=500, null=True, verbose_name='Data issues'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_points',
            field=models.TextField(blank=True, help_text=b' ', max_length=500, null=True, verbose_name='Data points'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='definition',
            field=models.TextField(blank=True, help_text=b' ', null=True, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, 'Direction of change (not applicable)'), (2, 'Positive (+)'), (3, 'Negative (-)')], default=1, help_text=b' ', null=True, verbose_name='Direction of Change'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='disaggregation',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='indicators.DisaggregationType', verbose_name='Disaggregation'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='indicators.IndicatorType', verbose_name='Indicator type'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='indicators.Level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='number',
            field=models.CharField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='program',
            field=models.ManyToManyField(help_text=b' ', to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='rationale_for_target',
            field=models.TextField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Rationale for target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='source',
            field=models.CharField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='indicatortype',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='indicatortype',
            name='description',
            field=models.TextField(blank=True, max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='indicatortype',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='indicatortype',
            name='indicator_type',
            field=models.CharField(blank=True, max_length=135, verbose_name='Indicator type'),
        ),
        migrations.AlterField(
            model_name='level',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='level',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=135, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(blank=True, max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.CharField(blank=True, max_length=135, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='customsort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Customsort'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='reportingfrequency',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='reportingfrequency',
            name='description',
            field=models.CharField(blank=True, max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reportingfrequency',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='reportingfrequency',
            name='frequency',
            field=models.CharField(blank=True, max_length=135, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='reportingperiod',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.ReportingFrequency', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='description',
            field=models.TextField(blank=True, max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='name',
            field=models.CharField(blank=True, max_length=135, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='country',
            field=models.ManyToManyField(blank=True, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='remote_owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remote owner'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='table_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Table id'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='unique_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unique count'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Url'),
        ),
    ]
