# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0063_auto_20171005_0709'),
        ('indicators', '0023_auto_20171004_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
