# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_auto_20171003_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolatable',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='remote_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
