# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0074_auto_20160331_1012'),
        ('indicators', '0034_auto_20160315_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolatable',
            name='country',
            field=models.ManyToManyField(blank=True, to='activitydb.Country'),
        ),
    ]
