# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0035_tolatable_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
