# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formlibrary', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, to='indicators.DisaggregationValue'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='training_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
    ]
