# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0002_auto_20170515_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='distribution',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='trainingattendance',
            old_name='program',
            new_name='workflowlevel1',
        ),
    ]
