# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('indicators', '0001_initial'),
        ('formlibrary', '0002_auto_20171019_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2', verbose_name='Project Initiation'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, to='indicators.DisaggregationValue'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='distribution_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='office_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Office'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2', verbose_name='Project Initiation'),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formlibrary.FieldType'),
        ),
        migrations.AddField(
            model_name='customform',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='distribution',
            field=models.ManyToManyField(blank=True, to='formlibrary.Distribution'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.SiteProfile'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='training',
            field=models.ManyToManyField(blank=True, to='formlibrary.TrainingAttendance'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='workflowlevel1',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1'),
        ),
    ]
