# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0002_auto_20170522_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingattendance',
            old_name='project_agreement',
            new_name='workflowlevel2',
        ),
    ]
