# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0003_auto_20170711_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomFormFields',
            new_name='CustomFormField',
        ),
        migrations.RenameField(
            model_name='customformfield',
            old_name='public',
            new_name='required',
        ),
    ]
