# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formlibrary', '0003_auto_20171019_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customforms', to=settings.AUTH_USER_MODEL),
        ),
    ]
