# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0004_customform_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customform',
            old_name='owner',
            new_name='created_by',
        ),
    ]
