# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20171204_0203'),
        ('formlibrary', '0004_customform_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='form_uuid',
            field=models.CharField(default='', max_length=255, verbose_name='CustomForm UUID'),
        ),
        migrations.AddField(
            model_name='customform',
            name='silo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customform',
            name='workflowlevel1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
    ]
