# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0004_auto_20170711_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
