# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0005_auto_20171204_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customform',
            name='form_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='CustomForm UUID'),
        ),
    ]
