# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20170707_0539'),
        ('formlibrary', '0006_auto_20170724_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='total_age_0_14_female',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_age_0_14_male',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_age_15_24_female',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_age_15_24_male',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_age_25_59_female',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_age_25_59_male',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_female',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_male',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='total_received_input',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_age_0_14_female',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_age_0_14_male',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_age_15_24_female',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_age_15_24_male',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_age_25_59_female',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_age_25_59_male',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_female',
        ),
        migrations.RemoveField(
            model_name='trainingattendance',
            name='total_male',
        ),
        migrations.AddField(
            model_name='distribution',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, to='indicators.DisaggregationValue'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, to='indicators.DisaggregationValue'),
        ),
    ]
