# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0006_auto_20171206_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('published', 'Published')], default='new', max_length=15, null=True),
        ),
    ]
