# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0007_customform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='is_template',
            field=models.BooleanField(default=0),
        ),
    ]
