# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0007_auto_20170727_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='distribution_indicator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator'),
        ),
    ]
