# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0009_auto_20180514_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='public',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), ('url', 'URL')], max_length=5, null=True),
        ),
    ]
