# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0009_auto_20170728_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customform',
            old_name='public',
            new_name='is_public',
        ),
    ]
