# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0010_auto_20170814_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
    ]
