# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-24 14:02
from __future__ import unicode_literals

from django.db import migrations
from ..models import CustomForm


def set_form_public(apps, schema_editor):
    CustomForm.objects.filter(is_public=True).update(
        public=CustomForm.PUBLIC_ALL)


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0010_customform_public'),
    ]

    operations = [
        migrations.RunPython(set_form_public),
    ]
