# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0011_customform_default_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='validations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='validations',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
