# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-06 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0011_set_customform_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customform',
            name='public',
        ),
    ]
