# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-07 11:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlibrary', '0012_remove_customform_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customform',
            name='public',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Public information with the structure:{org: (bool), url: (bool)}', null=True),
        ),
        migrations.AlterField(
            model_name='customform',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
