# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activitydb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name=b'Title')),
                ('narrative', models.TextField(blank=True, max_length=200, verbose_name=b'Narrative Text')),
                ('image_name', models.CharField(blank=True, max_length=50, verbose_name=b'Image URL')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('program_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name=b'Link to Service')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(b'gallery', b'Gallery'), (b'map', b'MapBox Map Layer')], max_length=255, null=True, verbose_name=b'Type of Link')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('link', models.ForeignKey(blank=True, max_length=200, on_delete=django.db.models.deletion.CASCADE, to='customdashboard.Link')),
                ('program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(blank=True, max_length=50, verbose_name=b'Project Status')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name=b'Status Description')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
