# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-15 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('customdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupyternotebooks',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1'),
        ),
    ]
