# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customdashboard', '0002_jupyternotebooks_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jupyternotebooks',
            old_name='program',
            new_name='workflowlevel1',
        ),
    ]
