# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0025_auto_20160825_1105'),
        ('customdashboard', '0003_overlaygroups_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterNotebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Notebook Name')),
                ('very_custom_dashboard', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Specialty Custom Dashboard Links')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'media', verbose_name=b'HTML/Jupyter Nontebook File')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.Program')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Jupyter Notebooks',
            },
        ),
    ]
