# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitydb', '0027_merge'),
        ('customdashboard', '0004_jupyternotebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramNarratives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative_title', models.CharField(blank=True, max_length=100, verbose_name=b'Narrative Title')),
                ('narrative', models.TextField(blank=True, verbose_name=b'Narrative Text')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activitydb.Program')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='program_name',
        ),
        migrations.RemoveField(
            model_name='overlaygroups',
            name='program',
        ),
        migrations.RemoveField(
            model_name='overlaynarratives',
            name='overlay_group',
        ),
        migrations.RemoveField(
            model_name='overlaynarratives',
            name='program',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='OverlayGroups',
        ),
        migrations.DeleteModel(
            name='OverlayNarratives',
        ),
    ]
