# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('awaiting_verification', 'Awaiting Verification'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('awaiting_verification', 'Awaiting Verification'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
