# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='historicalprojectagreement',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='historicalprojectcomplete',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='projectcomplete',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RenameField(
            model_name='tolabookmarks',
            old_name='program',
            new_name='workflowlevel1',
        ),
        migrations.RemoveField(
            model_name='projectagreement',
            name='program',
        ),
        migrations.AddField(
            model_name='projectagreement',
            name='workflowlevel1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='workflow.WorkflowLevel1', verbose_name='WorkflowLevel1'),
            preserve_default=False,
        ),
    ]
