# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='project_activity',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='project_design',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='project_activity',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='project_design',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='project_type',
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='parent_workflowlevel2',
            field=models.IntegerField(default=0, verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='parent_workflowlevel2',
            field=models.IntegerField(default=0, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='avg_household_size',
            field=models.DecimalField(blank=True, decimal_places=14, default=Decimal('0.00'), max_digits=25, null=True, verbose_name='Average Household Size'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='avg_household_size',
            field=models.DecimalField(blank=True, decimal_places=14, default=Decimal('0.00'), max_digits=25, null=True, verbose_name='Average Household Size'),
        ),
    ]
