# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-30 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170522_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benchmarks',
            new_name='WorkflowLevel3',
        ),
    ]
