# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20170711_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='evaluate',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='Evaluate',
        ),
    ]
