# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 10:42
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20171101_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='What was the actual final cost? This should match any financial documentation you have in the file. It should be completely documented and verifiable by finance and any potential audit', max_digits=20, verbose_name='Actual Cost'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='What was the actual final cost? This should match any financial documentation you have in the file. It should be completely documented and verifiable by finance and any potential audit', max_digits=20, verbose_name='Actual Cost'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflowlevel2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='donor_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_project', to='workflow.Currency'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='local_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_project', to='workflow.Currency'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Milestone'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='partners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Partner', verbose_name='Partners'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow2_sector', to='workflow.Sector', verbose_name='Sector'),
        ),
    ]
