# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170529_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_limit', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('approval_user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_approving', to='workflow.TolaUser')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country')),
            ],
            options={
                'ordering': ('approval_user',),
                'verbose_name_plural': 'WorkflowAccess',
            },
        ),
        migrations.RemoveField(
            model_name='approvalauthority',
            name='approval_user',
        ),
        migrations.RemoveField(
            model_name='approvalauthority',
            name='country',
        ),
        migrations.RemoveField(
            model_name='approvalauthority',
            name='workflowlevel1',
        ),
        migrations.AlterModelOptions(
            name='workflowlevel1',
            options={'ordering': ('name',), 'verbose_name_plural': 'WorkflowLevel1'},
        ),
        migrations.RenameField(
            model_name='workflowlevel1',
            old_name='gaitid',
            new_name='unique_id',
        ),
        migrations.RemoveField(
            model_name='workflowlevel1',
            name='budget_check',
        ),
        migrations.AddField(
            model_name='tolabookmarks',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, related_name='sub_sector', to='workflow.Sector'),
        ),
        migrations.DeleteModel(
            name='ApprovalAuthority',
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='workflowlevel1',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1'),
        ),
    ]
