# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 12:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170712_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='activity_sort',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='project_sort',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='activity_sort',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
