# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20171101_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalworkflow',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='documentation',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='historicalbudget',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='historicalsiteprofile',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='historicalworkflowlevel2',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='siteprofile',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='workflowlevel2',
            old_name='owner',
            new_name='created_by',
        ),
    ]
