# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20171109_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='workflowlevel1',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1'),
        ),
    ]
