# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-30 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20170530_0039'),
        ('workflow', '0004_auto_20170530_0456'),
    ]

    operations = [
    ]
