# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='community_handover',
            field=models.BooleanField(default=False, help_text='Check box if it was completed', verbose_name='CommunityHandover/Sustainability Maintenance Plan'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='on_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='community_handover',
            field=models.BooleanField(default=False, help_text='Check box if it was completed', verbose_name='CommunityHandover/Sustainability Maintenance Plan'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='on_time',
            field=models.BooleanField(default=True),
        ),
    ]
