# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20170714_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowlevel3',
            options={'ordering': ('description',), 'verbose_name_plural': 'WorkflowLevel3'},
        ),
    ]
