# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20170601_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, choices=[('workflowlevel1', 'Workflow Level 1'), ('workflowlevel2', 'Workflow Level 2'), ('workflowlevel3', 'Workflow Level 3'), ('sites', 'Sites'), ('stakeholders', 'Stakeholders'), ('documents', 'Documents')], max_length=3, null=True)),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Status')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('approval_type', 'approval_user'),
            },
        ),
        migrations.CreateModel(
            name='ApprovalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization')),
            ],
            options={
                'ordering': ('name', 'organization'),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(blank=True, max_length=255, verbose_name='Source Currency Name')),
                ('target_currency', models.CharField(blank=True, max_length=255, verbose_name='Target Currency Name')),
                ('current_rate', models.IntegerField(blank=True, null=True, verbose_name='Conversion Rate')),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('source_currency',),
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='account_code',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Accounting Code'),
        ),
        migrations.AddField(
            model_name='budget',
            name='actual_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='budget',
            name='cost_center',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='budget',
            name='donor_code',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Donor Code'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='account_code',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Accounting Code'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='actual_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Actual'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='cost_center',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='donor_code',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Donor Code'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='workflow.ApprovalType'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approval_user',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authuser', to='workflow.TolaUser'),
        ),
        migrations.AddField(
            model_name='budget',
            name='donor_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='budget',
            name='local_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='donor_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='historicalbudget',
            name='local_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Currency'),
        ),
    ]
