# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_auto_20171122_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('source_currency',), 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkflowlevel2',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Workflow Level 2'},
        ),
        migrations.AlterModelOptions(
            name='tolabookmarks',
            options={'ordering': ('name',), 'verbose_name_plural': 'Tola Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='tolasites',
            options={'verbose_name': 'Tola Site', 'verbose_name_plural': 'Tola Sites'},
        ),
        migrations.AlterModelOptions(
            name='workflowlevel1',
            options={'ordering': ('name',), 'verbose_name': 'Workflow Level 1', 'verbose_name_plural': 'Workflow Level 1'},
        ),
        migrations.AlterModelOptions(
            name='workflowlevel1sector',
            options={'ordering': ('create_date',), 'verbose_name': 'Workflow Level 1 Sector', 'verbose_name_plural': 'Workflow Level 1 Sectors'},
        ),
        migrations.AlterModelOptions(
            name='workflowlevel2',
            options={'ordering': ('name',), 'permissions': (('can_approve', 'Can approve initiation'),), 'verbose_name': 'Workflow Level 2', 'verbose_name_plural': 'Workflow Level 2'},
        ),
        migrations.AlterModelOptions(
            name='workflowlevel2sort',
            options={'ordering': ('workflowlevel1', 'workflowlevel2_id'), 'verbose_name': 'Workflow Level 2 Sort', 'verbose_name_plural': 'Workflow Level 2 Sort'},
        ),
        migrations.AlterModelOptions(
            name='workflowlevel3',
            options={'ordering': ('description',), 'verbose_name': 'Workflow Level 3', 'verbose_name_plural': 'Workflow Level 3'},
        ),
        migrations.AlterModelOptions(
            name='workflowmodules',
            options={'ordering': ('modules',), 'verbose_name_plural': 'Workflow Modules'},
        ),
        migrations.AlterModelOptions(
            name='workflowteam',
            options={'ordering': ('workflow_user',), 'verbose_name': 'Workflow Team', 'verbose_name_plural': 'Workflow Teams'},
        ),
    ]
