# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170620_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='sector',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='notes',
            field=models.TextField(blank=True, max_length=765, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='workflow.Sector'),
        ),
    ]
