# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20171204_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolasites',
            name='whitelisted_domains',
            field=models.TextField(blank=True, null=True, verbose_name='Whitelisted Domains'),
        ),
    ]
