# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_auto_20170719_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='template',
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
