# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20170626_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='community_project_description',
            field=models.TextField(blank=True, help_text='Description must describe how the Community Proposal meets the project criteria', null=True, verbose_name='Describe the project you would like to be considered'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='project_name',
            field=models.CharField(help_text='Please be specific in your name.  Consider that the name includes WHO, WHAT, WHERE, HOW', max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='community_project_description',
            field=models.TextField(blank=True, help_text='Description must describe how the Community Proposal meets the project criteria', null=True, verbose_name='Describe the project you would like to be considered'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='project_name',
            field=models.CharField(help_text='Please be specific in your name.  Consider that the name includes WHO, WHAT, WHERE, HOW', max_length=255, verbose_name='Project Name'),
        ),
    ]
