# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20170721_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='level2_uuid',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=255, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='parent_workflowlevel2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='sort',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='level2_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='parent_workflowlevel2',
            field=models.IntegerField(blank=True, default=0, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='sort',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
