# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-09 14:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_tolasites_whitelisted_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('share', models.ManyToManyField(blank=True, to='workflow.TolaUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toladashboard', to='workflow.TolaUser')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Dashboards',
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('xSm', models.IntegerField(default=0)),
                ('ySm', models.IntegerField(default=0)),
                ('xMd', models.IntegerField(default=0)),
                ('yMd', models.IntegerField(default=0)),
                ('xLg', models.IntegerField(default=0)),
                ('yLg', models.IntegerField(default=0)),
                ('xXl', models.IntegerField(default=0)),
                ('yXl', models.IntegerField(default=0)),
                ('drag_and_drop', models.BooleanField(default=0)),
                ('resizable', models.BooleanField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('title',),
                'verbose_name_plural': 'Widgets',
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widgets',
            field=models.ManyToManyField(blank=True, to='workflow.Widget'),
        ),
    ]
