# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20170628_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('awaiting_verification', 'Awaiting Verification'), ('closed', 'Closed')], default='open', max_length=50)),
                ('section', models.CharField(choices=[('workflowlevel1', 'Workflow Level 1'), ('workflowlevel2', 'Workflow Level 2'), ('workflowlevel3', 'Workflow Level 3'), ('sites', 'Sites'), ('stakeholders', 'Stakeholders'), ('documents', 'Documents')], default='workflowlevel1', max_length=50)),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_type', to='workflow.ApprovalType')),
                ('assigned_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_approval', to='workflow.TolaUser')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_approval', to='workflow.TolaUser')),
            ],
            options={
                'ordering': ('approval_type',),
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('note_content', models.TextField(blank=True, verbose_name='Name')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('note_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_from', to='workflow.TolaUser')),
                ('note_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_to', to='workflow.TolaUser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization')),
            ],
            options={
                'ordering': ('name', 'organization'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(choices=[('approval', 'Approval'), ('budget', 'Budget'), ('stakeholders', 'Stakeholders'), ('documents', 'Documents')], default='open', max_length=50)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('workflowlevel2', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2')),
            ],
            options={
                'ordering': ('modules',),
            },
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approval_type',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approval_user',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_notes', to='workflow.Notes'),
        ),
    ]
