# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_workflowlevel2_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='office',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='account_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='workflowmodules',
            name='workflowlevel2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2'),
        ),
    ]
