# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20170630_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel2',
            name='workflowlevel1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowlevel2', to='workflow.WorkflowLevel1', verbose_name='Program'),
        ),
    ]
