# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20180110_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='changed',
            field=models.BooleanField(default=0),
        ),
    ]
