# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_auto_20170729_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowmodules',
            name='modules',
            field=models.CharField(choices=[('approval', 'Approval'), ('budget', 'Budget'), ('stakeholders', 'Stakeholders'), ('documents', 'Documents'), ('risk_issues', 'Risks and Issues'), ('sites', 'Sites'), ('procurement_plan', 'Procurement Plan')], default='open', max_length=50),
        ),
    ]
