# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workflow', '0012_widget_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='chargebee_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='chargebee_used_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
