# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 08:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20180122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='oauth_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OAuth Domains'), blank=True, null=True, size=None),
        ),
    ]
