# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 13:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20180122_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlevel3',
            name='site',
        ),
        migrations.RemoveField(
            model_name='workflowlevel3',
            name='workflowlevel2',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='actual_cost_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='agency_cost',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='budget_variance',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='community_handover',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='date_of_request',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='explanation_of_variance',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='no_explanation',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='on_time',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='short',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='actual_cost_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='agency_cost',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='budget_variance',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='community_handover',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='date_of_request',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='explanation_of_variance',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='no_explanation',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='on_time',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='short',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='sort',
        ),
        migrations.AlterField(
            model_name='budget',
            name='account_code',
            field=models.CharField(blank=True, help_text='Label or coded field', max_length=135, null=True, verbose_name='Accounting Code'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='actual_value',
            field=models.IntegerField(blank=True, default=0, help_text='Monetary value positive or negative', null=True, verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='contributor',
            field=models.CharField(blank=True, help_text='Source of budget fund', max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Associate a cost with a type of expense', max_length=135, null=True, verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='description_of_contribution',
            field=models.CharField(blank=True, help_text='Purpose or use for funds', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='donor_code',
            field=models.CharField(blank=True, help_text='Third Party coded field', max_length=135, null=True, verbose_name='Donor Code'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='donor_currency',
            field=models.ForeignKey(blank=True, help_text='Secondary Currency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='workflow.Currency'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='local_currency',
            field=models.ForeignKey(blank=True, help_text='Primary Currency', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='workflow.Currency'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, help_text='Approximate value if not a monetary fund', null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, help_text='Releated workflow level 2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel2'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='account_code',
            field=models.CharField(blank=True, help_text='Label or coded field', max_length=135, null=True, verbose_name='Accounting Code'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='actual_value',
            field=models.IntegerField(blank=True, default=0, help_text='Monetary value positive or negative', null=True, verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='contributor',
            field=models.CharField(blank=True, help_text='Source of budget fund', max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Associate a cost with a type of expense', max_length=135, null=True, verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='description_of_contribution',
            field=models.CharField(blank=True, help_text='Purpose or use for funds', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='donor_code',
            field=models.CharField(blank=True, help_text='Third Party coded field', max_length=135, null=True, verbose_name='Donor Code'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='proposed_value',
            field=models.IntegerField(blank=True, default=0, help_text='Approximate value if not a monetary fund', null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Cost to date calculated from Budget Module', max_digits=20, verbose_name='Actual Cost'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='capacity_built',
            field=models.TextField(blank=True, help_text='Descriptive, did this help increases internal or external capacity', max_length=755, null=True, verbose_name='Describe how sustainability was ensured for this project?'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the overall effort', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='description_of_community_involvement',
            field=models.TextField(blank=True, help_text='Descriptive, what community orgs are groups are involved', null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='description_of_government_involvement',
            field=models.TextField(blank=True, help_text='Descriptive, what government entities might be involved', null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='effect_or_impact',
            field=models.TextField(blank=True, help_text='Descriptive, what is the anticipated outcome of the effort', null=True, verbose_name='What is the anticipated Outcome or Goal?'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='issues_and_challenges',
            field=models.TextField(blank=True, help_text='Descriptive, what are some of the issues and challenges', null=True, verbose_name='List any issues or challenges faced (include reasons for delays)'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='justification_background',
            field=models.TextField(blank=True, help_text='Descriptive, why are we starting this effort', null=True, verbose_name='General Background and Problem Statement'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Descriptive, when completed what lessons were learned', null=True, verbose_name='Lessons learned'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='level2_uuid',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, help_text='Unique ID', max_length=255, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='quality_assured',
            field=models.TextField(blank=True, help_text='Descriptive, how was the overall quality assured for this effort', max_length=755, null=True, verbose_name='How was quality assured for this project'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='risks_assumptions',
            field=models.TextField(blank=True, help_text='Descriptive, what are the risks associated', null=True, verbose_name='Risks and Assumptions'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='short_name',
            field=models.CharField(blank=True, help_text='Shortened name autogenerated', max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='total_estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total budget to date calculated from Budget Module', max_digits=12, verbose_name='Total Project Budget'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='award',
            field=models.ManyToManyField(blank=True, help_text='Funding source if used', to='workflow.Award'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Coded field for financial system integrations', max_length=255, null=True, verbose_name='Fund Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='country',
            field=models.ManyToManyField(blank=True, help_text='Country location for work', to='workflow.Country'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='fund_code',
            field=models.ManyToManyField(blank=True, help_text='Coded field for financial system integrations', to='workflow.FundCode'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='funding_status',
            field=models.CharField(blank=True, help_text='Funds have been approved to start working', max_length=255, verbose_name='Funding Status'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='milestone',
            field=models.ManyToManyField(blank=True, help_text='Set of milestones or stated goals and dates for work', to='workflow.Milestone'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Related Org to associate with', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='Combine with a set or other level 1s for folder like structure', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Portfolio'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='public_dashboard',
            field=models.BooleanField(default=False, help_text='Allow dashboards to be set to public if needed', verbose_name='Enable Public Dashboard'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='sector',
            field=models.ManyToManyField(blank=True, help_text='Primary work type classification', to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, help_text='Additional work type classifications', related_name='sub_sector', to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='unique_id',
            field=models.CharField(blank=True, help_text='User facing unique ID field if needed', max_length=255, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Cost to date calculated from Budget Module', max_digits=20, verbose_name='Actual Cost'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='approval',
            field=models.ManyToManyField(blank=True, help_text='Multiple approval level and users', to='workflow.ApprovalWorkflow'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='capacity_built',
            field=models.TextField(blank=True, help_text='Descriptive, did this help increases internal or external capacity', max_length=755, null=True, verbose_name='Describe how sustainability was ensured for this project?'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the overall effort', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='description_of_community_involvement',
            field=models.TextField(blank=True, help_text='Descriptive, what community orgs are groups are involved', null=True),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='description_of_government_involvement',
            field=models.TextField(blank=True, help_text='Descriptive, what government entities might be involved', null=True),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='donor_currency',
            field=models.ForeignKey(blank=True, help_text='Secondary Currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_project', to='workflow.Currency'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='effect_or_impact',
            field=models.TextField(blank=True, help_text='Descriptive, what is the anticipated outcome of the effort', null=True, verbose_name='What is the anticipated Outcome or Goal?'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='issues_and_challenges',
            field=models.TextField(blank=True, help_text='Descriptive, what are some of the issues and challenges', null=True, verbose_name='List any issues or challenges faced (include reasons for delays)'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='justification_background',
            field=models.TextField(blank=True, help_text='Descriptive, why are we starting this effort', null=True, verbose_name='General Background and Problem Statement'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Descriptive, when completed what lessons were learned', null=True, verbose_name='Lessons learned'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='level2_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text='Unique ID', max_length=255, unique=True, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='local_currency',
            field=models.ForeignKey(blank=True, help_text='Primary Currency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_project', to='workflow.Currency'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Association with a Workflow Level 1 Milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Milestone'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Primary office for effort', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='quality_assured',
            field=models.TextField(blank=True, help_text='Descriptive, how was the overall quality assured for this effort', max_length=755, null=True, verbose_name='How was quality assured for this project'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='risks_assumptions',
            field=models.TextField(blank=True, help_text='Descriptive, what are the risks associated', null=True, verbose_name='Risks and Assumptions'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Primary Sector or type of work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow2_sector', to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='short_name',
            field=models.CharField(blank=True, help_text='Shortened name autogenerated', max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='site',
            field=models.ManyToManyField(blank=True, help_text='Geographic sites or locations', to='workflow.SiteProfile'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='staff_responsible',
            field=models.ForeignKey(blank=True, help_text='Responsible party', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.TolaUser'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, help_text='Other parties involved in effort', to='workflow.Stakeholder', verbose_name='Stakeholders'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, help_text='Secondary sector or type of work', related_name='workflowlevel2_sub_sector', to='workflow.Sector', verbose_name='Sub-Sector'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='total_estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Total budget to date calculated from Budget Module', max_digits=12, verbose_name='Total Project Budget'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='workflowlevel1',
            field=models.ForeignKey(help_text='Primary Workflow', on_delete=django.db.models.deletion.CASCADE, related_name='workflowlevel2', to='workflow.WorkflowLevel1', verbose_name='Program'),
        ),
        migrations.DeleteModel(
            name='WorkflowLevel3',
        ),
    ]
