# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20180122_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='data_source',
            field=models.CharField(default='program', max_length=255),
            preserve_default=False,
        ),
    ]
