# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20170814_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaccess',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowaccess',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
