# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-15 05:28
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_organization_oauth_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel3',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Estimated Budget'),
        ),
        migrations.AlterField(
            model_name='workflowlevel3',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Actual Cost'),
        ),
    ]
