# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20170706_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='document_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Document UUID'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='site_uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255, verbose_name='Site UUID'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='level2_uuid',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=255, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='site_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Site UUID'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='stakeholder_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Stakeholder UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='level1_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='WorkflowLevel1 UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='level2_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='WorkflowLevel2 UUID'),
        ),
        migrations.AlterField(
            model_name='workflowlevel3',
            name='level3_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='WorkflowLevel3 UUID'),
        ),
    ]
