# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20170706_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalworkflow',
            old_name='assigned_from',
            new_name='requested_from',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='approval_remarks',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='approval_submitted_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='approved_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='approval_remarks',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='approval_submitted_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='approved_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='approval',
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='approval',
            field=models.ManyToManyField(blank=True, to='workflow.ApprovalWorkflow'),
        ),
    ]
