# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20170706_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note_from',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='note_to',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='historicalsiteprofile',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='historicalsiteprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalsiteprofile',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='historicalsiteprofile',
            name='location_verified_by',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='location_verified_by',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='notes',
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='approval',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='approval',
            field=models.ManyToManyField(blank=True, to='workflow.ApprovalWorkflow'),
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='approval',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='approval',
            field=models.ManyToManyField(blank=True, to='workflow.ApprovalWorkflow'),
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
