# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20170623_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ('item',), 'verbose_name': 'Checklist Item'},
        ),
        migrations.AlterModelOptions(
            name='formguidance',
            options={'ordering': ('create_date',), 'verbose_name': 'Form Guidance'},
        ),
        migrations.AlterModelOptions(
            name='fundcode',
            options={'ordering': ('name',), 'verbose_name': 'Fund Code'},
        ),
        migrations.AlterModelOptions(
            name='landtype',
            options={'ordering': ('classify_land',), 'verbose_name': 'Land Type'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('name',), 'verbose_name': 'Office'},
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'ordering': ('profile',), 'verbose_name': 'Profile Type'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('name',), 'verbose_name': 'Program'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'ordering': ('name',), 'verbose_name': 'Project Type'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('sector',), 'verbose_name': 'Sector'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('name',), 'verbose_name': 'Template'},
        ),
        migrations.AlterModelOptions(
            name='tolabookmarks',
            options={'ordering': ('name',), 'verbose_name': 'Tola Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='tolauser',
            options={'ordering': ('name',), 'verbose_name': 'Tola User'},
        ),
        migrations.AlterField(
            model_name='approvalauthority',
            name='approval_user',
            field=models.ForeignKey(blank=True, help_text='User with Approval Authority', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_approving', to='workflow.TolaUser', verbose_name='Tola User'),
        ),
        migrations.AlterField(
            model_name='approvalauthority',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ProjectComplete', verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='est_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Est end date'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='est_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Est start date'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.SiteProfile', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProjectComplete', verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='contributor',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Contributor'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='description_of_contribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of contribution'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.CharField(blank=True, default='Checklist', max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Checklist', verbose_name='Checklist'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='item',
            field=models.CharField(max_length=255, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.TolaUser', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='country',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='country',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ProjectAgreement', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Template', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='formguidance',
            name='form',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='formguidance',
            name='guidance',
            field=models.TextField(blank=True, null=True, verbose_name='Guidance'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='contributor',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Contributor'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='description_of_contribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of contribution'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='description_of_community_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Description of community involvement'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='description_of_government_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Description of government involvement'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='description_of_project_activities',
            field=models.TextField(blank=True, null=True, verbose_name='Description of project activities'),
        ),
        migrations.AlterField(
            model_name='historicalprojectagreement',
            name='estimation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimation date'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='actual_cost_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual cost date'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='actual_duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual duaration'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, help_text='Imported from Project Initiation', null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, help_text='Imported Project Initiation', null=True, verbose_name='Expected end date'),
        ),
        migrations.AlterField(
            model_name='historicalprojectcomplete',
            name='expected_start_date',
            field=models.DateTimeField(blank=True, help_text='Imported from Project Initiation', null=True, verbose_name='Expected start date'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='male_6_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Male age 6-9'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='total_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total female'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='total_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total male'),
        ),
        migrations.AlterField(
            model_name='historicalsiteprofile',
            name='total_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total population'),
        ),
        migrations.AlterField(
            model_name='loggeduser',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='loggeduser',
            name='email',
            field=models.CharField(default='user@mercycorps.com', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='loggeduser',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ProjectComplete', verbose_name='complete'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization url'),
        ),
        migrations.AlterField(
            model_name='program',
            name='country',
            field=models.ManyToManyField(to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='program',
            name='fund_code',
            field=models.ManyToManyField(blank=True, to='workflow.FundCode', verbose_name='Fund code'),
        ),
        migrations.AlterField(
            model_name='program',
            name='sector',
            field=models.ManyToManyField(blank=True, to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by_agreement', to='workflow.TolaUser', verbose_name='Approval submitted by'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checking', to='workflow.TolaUser', verbose_name='Checked by'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='description_of_community_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Description of community involvement'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='description_of_government_involvement',
            field=models.TextField(blank=True, null=True, verbose_name='Description of government involvement'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='description_of_project_activities',
            field=models.TextField(blank=True, null=True, verbose_name='Description of project activities'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='estimation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimation date'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='evaluate',
            field=models.ManyToManyField(blank=True, to='workflow.Evaluate', verbose_name='Evaluate'),
        ),
        migrations.AlterField(
            model_name='projectagreement',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_reviewing', to='workflow.TolaUser', verbose_name='Finance reviewed by'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='actual_cost_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual cost date'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='actual_duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual duaration'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, help_text='Imported from Project Initiation', null=True, verbose_name='Actual start date'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by_complete', to='workflow.TolaUser', verbose_name='Approval submitted by'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approving_agreement_complete', to='workflow.TolaUser', verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checking_complete', to='workflow.TolaUser', verbose_name='Checked by'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='estimated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimating_complete', to='workflow.TolaUser', verbose_name='Estimated by'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, help_text='Imported Project Initiation', null=True, verbose_name='Expected end date'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='expected_start_date',
            field=models.DateTimeField(blank=True, help_text='Imported from Project Initiation', null=True, verbose_name='Expected start date'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complete', to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='project_type',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ProjectType', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewing_complete', to='workflow.TolaUser', verbose_name='Reviewed by'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='site',
            field=models.ManyToManyField(blank=True, to='workflow.SiteProfile', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='projectcomplete',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, to='workflow.Stakeholder', verbose_name='Stakeholder'),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='description',
            field=models.CharField(max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='This is the Provincial Line Manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_approving', to='workflow.TolaUser', verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='classify_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.LandType', verbose_name='Classify land'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='filled_by',
            field=models.ForeignKey(blank=True, help_text='This is the originator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_estimate', to='workflow.TolaUser', verbose_name='Filled by'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='location_verified_by',
            field=models.ForeignKey(blank=True, help_text='This should be GIS Manager', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comm_gis', to='workflow.TolaUser', verbose_name='Location verified by'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='male_6_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Male age 6-9'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='total_female',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total female'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='total_male',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total male'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='total_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total population'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.ProfileType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stake_approving', to='workflow.TolaUser', verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='contact',
            field=models.ManyToManyField(blank=True, max_length=255, to='workflow.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='filled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stake_filled', to='workflow.TolaUser', verbose_name='Filled by'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='notes',
            field=models.TextField(blank=True, max_length=765, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='sectors',
            field=models.ManyToManyField(blank=True, to='workflow.Sector', verbose_name='Sectors'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.StakeholderType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(max_length=765, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='bookmark_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bookmark url'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='tolabookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolabookmark', to='workflow.TolaUser', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agency name'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='agency_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agency url'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='privacy_disclaimer',
            field=models.TextField(blank=True, null=True, verbose_name='Privacy disclaimer'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='tola_report_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tola report url'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='tola_tables_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tola tables token'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='tola_tables_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tola tables url'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='tola_tables_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tola tables user'),
        ),
        migrations.AlterField(
            model_name='tolasites',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='organization',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.')], max_length=3, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tola_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.District', verbose_name='District'),
        ),
    ]
