# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_historicalissueregister_historicalriskregister_issueregister_riskregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissueregister',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalissueregister',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.WorkflowLevel2'),
        ),
        migrations.AddField(
            model_name='historicalriskregister',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.WorkflowLevel2'),
        ),
        migrations.AddField(
            model_name='issueregister',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueregister',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2'),
        ),
        migrations.AddField(
            model_name='riskregister',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2'),
        ),
    ]
