# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-26 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20180223_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='default_language',
        ),
    ]
