# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 16:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20180302_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='proposed_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Approximate value if not a monetary fund', max_digits=12, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='proposed_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Approximate value if not a monetary fund', max_digits=12, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monetary value positive or negative', max_digits=12, verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='historicalbudget',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Monetary value positive or negative', max_digits=12, verbose_name='Actual'),
        ),
    ]
