# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20170815_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Name')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Type')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Default Value')),
                ('api_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Associated API URL')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Associated API Token')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization')),
            ],
            options={
                'ordering': ('name', 'type'),
                'verbose_name_plural': 'CodedFields',
            },
        ),
        migrations.CreateModel(
            name='CodedFieldValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('coded_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.CodedField')),
            ],
            options={
                'ordering': ('value', 'coded_field', 'workflowlevel2__name'),
                'verbose_name_plural': 'CodedFields',
            },
        ),
        migrations.CreateModel(
            name='WorkflowLevel2Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflowlevel2_id', models.IntegerField(default=0, verbose_name='ID to be Sorted')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('workflowlevel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel1')),
            ],
            options={
                'ordering': ('workflowlevel1', 'sort_order', 'workflowlevel2_id'),
                'verbose_name_plural': 'WorkflowLevel Sort',
            },
        ),
        migrations.AlterModelOptions(
            name='workflowlevel2',
            options={'ordering': ('name',), 'permissions': (('can_approve', 'Can approve initiation'),), 'verbose_name_plural': 'WorkflowLevel2'},
        ),

        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='activity_code',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='average_household_size',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='checked_by_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='cod_num',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='community_project_description',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='description_of_project_activities',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='estimated_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='estimated_by_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='estimated_num_direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='estimated_num_indirect_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='estimation_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='exchange_rate_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='expected_duration',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='finance_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='finance_reviewed_by_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='has_rej_letter',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='justification_description_community_selection',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='lin_code',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='local_agency_cost',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='local_mc_estimated_budget',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='local_total_cost',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='local_total_estimated_budget',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='me_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='me_reviewed_by_date',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='name_of_partners',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='project_activity',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='reviewed_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='activity_code',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='average_household_size',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='beneficiary_type',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='checked_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='cod_num',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='community_project_description',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='description_of_project_activities',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='estimated_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='estimated_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='estimated_num_direct_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='estimated_num_indirect_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='estimation_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='exchange_rate_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='expected_duration',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='finance_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='finance_reviewed_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='has_rej_letter',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='justification_description_community_selection',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='lin_code',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='local_agency_cost',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='local_mc_estimated_budget',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='local_total_cost',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='local_total_estimated_budget',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='me_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='me_reviewed_by_date',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='name_of_partners',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='project_activity',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='reviewed_by_date',
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='donor_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='local_currency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='donor_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_project', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='local_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_project', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Project Code'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='sub_sector',
            field=models.ManyToManyField(blank=True, related_name='workflowlevel2_sub_sector', to='workflow.Sector', verbose_name='Sub-Sector'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow2_sector', to='workflow.Sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='codedfieldvalues',
            name='workflowlevel2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.WorkflowLevel2'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='coded_fields',
            field=models.ManyToManyField(blank=True, to='workflow.CodedField'),
        ),
    ]
