# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_remove_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='public_all',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='public_in_org',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='public',
            field=models.CharField(blank=True, null=True, choices=[('org', 'Organization'), ('all', 'All')], max_length=5),
        ),
    ]
