# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20170815_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='partners',
        ),
    ]
