# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20170815_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_uuid', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Partner UUID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partner/Organization Name')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ManyToManyField(blank=True, to='workflow.ApprovalWorkflow')),
                ('contact', models.ManyToManyField(blank=True, max_length=255, to='workflow.Contact')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country')),
                ('sectors', models.ManyToManyField(blank=True, to='workflow.Sector')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.StakeholderType')),
            ],
            options={
                'ordering': ('country', 'name', 'type'),
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='partners',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflow.Partner'),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='partners',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Partner', verbose_name='Partners'),
        ),
    ]
