# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20180309_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product identifier')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('workflowlevel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workflow.WorkflowLevel2')),
            ],
        ),
    ]
