# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 09:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_product'),
    ]

    operations = [
        HStoreExtension(), # https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#hstorefield
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='address',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Address object with the structure: street (string), house_number (string), postal_code: (string), city (string), country (string)', null=True),
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='site_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='address',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Address object with the structure: street (string), house_number (string), postal_code: (string), city (string), country (string)', null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='site_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
