# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_budget_decimal',
            field=models.BooleanField(default=True, verbose_name='Allow Budget in Decimal'),
        ),
    ]
