# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20170815_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkflowlevel2',
            old_name='actual_budget',
            new_name='actual_cost',
        ),
        migrations.RenameField(
            model_name='historicalworkflowlevel2',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='historicalworkflowlevel2',
            old_name='mc_estimated_budget',
            new_name='org_estimated_budget',
        ),
        migrations.RenameField(
            model_name='workflowlevel2',
            old_name='actual_budget',
            new_name='actual_cost',
        ),
        migrations.RenameField(
            model_name='workflowlevel2',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workflowlevel2',
            old_name='mc_estimated_budget',
            new_name='org_estimated_budget',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='coded_fields',
        ),
        migrations.AddField(
            model_name='codedfield',
            name='is_required',
            field=models.BooleanField(default=0, verbose_name='Required Field?'),
        ),
        migrations.AddField(
            model_name='codedfield',
            name='is_universal',
            field=models.BooleanField(default=0, verbose_name='Available in Every Level 2 Form?'),
        ),
        migrations.AddField(
            model_name='codedfield',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Label'),
        ),
        migrations.AddField(
            model_name='codedfield',
            name='workflowlevel1',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='codedfield',
            name='workflowlevel2',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel2'),
        ),
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='name',
            field=models.CharField(default='Temporary', max_length=255, verbose_name='Project Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='name',
            field=models.CharField(default='Temporary', max_length=255, verbose_name='Project Name'),
            preserve_default=False,
        ),
    ]
