# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20170816_0134'),
    ]

    operations = [

        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
    ]
