# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20170817_0045'),
    ]

    operations = [

        migrations.AddField(
            model_name='workflowlevel1',
            name='award',
            field=models.ManyToManyField(blank=True, to='workflow.Award'),
        ),
        migrations.AlterField(
            model_name='workflowlevel1',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID'),
        ),
    ]
