# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20180425_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='dashboard_uuid',
            field=models.UUIDField(blank=True, null=True, default=None, verbose_name='Dashboard UUID'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='public_url_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='public',
            field=models.CharField(blank=True, choices=[('org', 'Organization'), ('url', 'URL'), ('all', 'All')], max_length=5, null=True),
        ),
    ]
