# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20180620_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
