# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-14 11:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_organization_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='public',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='public',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Public information with the structure:{all: (bool), org: (bool), url: (bool)}', null=True),
        ),
    ]
