# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_internationalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='org_estimated_budget',
        )
    ]
