# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_organization_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.SiteProfile'),
        ),
    ]
