# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-13 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0027_auto_20180810_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='public',
        ),
    ]
