# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20170822_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='progress',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('awaitingapproval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowlevel2',
            name='progress',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('awaitingapproval', 'Awaiting Approval'), ('tracking', 'Tracking'), ('closed', 'Closed')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'RED')], default='green', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'RED')], default='green', max_length=50),
        ),
    ]
