# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-31 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20180816_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalworkflowlevel2',
            name='address',
        ),
        migrations.RemoveField(
            model_name='workflowlevel2',
            name='address',
        ),
    ]
