# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-07 14:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.db.utils import ProgrammingError


def create_fields(apps, schema_editor):
    # If fields are not there, add them. If they were added before, then
    # ignore the error.
    try:
        migrations.AddField(
            model_name='historicalworkflowlevel2',
            name='address',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Address object with the structure: street (string), house_number (string), postal_code: (string), city (string), country (string)', null=True),
        )
        migrations.AddField(
            model_name='workflowlevel2',
            name='address',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Address object with the structure: street (string), house_number (string), postal_code: (string), city (string), country (string)', null=True),
        )
    except ProgrammingError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20180831_0452'),
    ]

    operations = [
        migrations.RunPython(create_fields),
    ]
