# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_auto_20170822_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'REd')], default='green', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowlevel2',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'REd')], default='green', max_length=50),
        ),
    ]
