# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_auto_20170823_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('default_global', models.BooleanField(default=0)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='approvaltype',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='award_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_currency', to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='award',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Currency'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.TolaUser'),
        ),
        migrations.AddField(
            model_name='formguidance',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='formguidance',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='fundcode',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='fundcode',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='landtype',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='landtype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='sector',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='sector',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='default_global',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='approvaltype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='award',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AlterField(
            model_name='codedfield',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Phase'),
        ),
    ]
