# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_auto_20181024_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
