# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_auto_20170823_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
