# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_documentation_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL (Link to document or document repository)'),
        ),
    ]
