# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_auto_20181206_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='approval_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_type', to='workflow.ApprovalType'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.ProfileType'),
        ),
    ]
