# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20190213_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Related Org to associate with', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
