# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20190213_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='tola_user_uuid',
            field=models.CharField(default='ryruuiwwoqjjkeke', max_length=255, verbose_name='TolaUser UUID'),
            preserve_default=False,
        ),
    ]
