# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_dashboard_tola_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='tola_user_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TolaUser UUID'),
        ),
    ]
