# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_dashboard_tola_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='tola_user_uuid',
            new_name='created_by',
        ),
    ]
