# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_auto_20170831_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='workflowlevel1',
        ),
        migrations.RemoveField(
            model_name='workflowlevel1',
            name='phase',
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='milestone',
            field=models.ManyToManyField(blank=True, to='workflow.Milestone'),
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
