# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_auto_20170904_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('budget_limit', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Country')),
                ('partner_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization')),
                ('workflow_user', models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_approving', to='workflow.TolaUser')),
                ('workflowlevel1', models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1')),
            ],
            options={
                'ordering': ('workflow_user',),
                'verbose_name_plural': 'WorkflowTeam',
            },
        ),
        migrations.RemoveField(
            model_name='workflowaccess',
            name='country',
        ),
        migrations.RemoveField(
            model_name='workflowaccess',
            name='workflow_user',
        ),
        migrations.RemoveField(
            model_name='workflowaccess',
            name='workflowlevel1',
        ),
        migrations.DeleteModel(
            name='WorkflowAccess',
        ),
    ]
