# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-27 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_auto_20190226_2147'),
        ('workflow', '0034_office_organization'),
    ]

    operations = [
    ]
