# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_auto_20170905_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='contribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contribution'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='stakeholder_register',
            field=models.BooleanField(default=0, verbose_name='Has this partner been added to stakeholder register?'),
        ),
    ]
