# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 07:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20170906_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolauser',
            name='filter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
