# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 13:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20190306_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='blacklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_wfl1_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
