# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20190306_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
