# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 13:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_auto_20190308_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='blacklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='shared_wfl1_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=[], size=None),
        ),
    ]
