# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_tolauser_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document'),
        ),
    ]
