# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_auto_20190308_0546'),
        ('workflow', '0038_auto_20190311_2249'),
    ]

    operations = [
    ]
