# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_auto_20170915_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowlevel1',
            name='country',
            field=models.ManyToManyField(blank=True, to='workflow.Country'),
        ),
    ]
