# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_merge_20190312_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='TolaData', max_length=255, unique=True, verbose_name='Organization Name'),
        ),
    ]
