# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_merge_20190312_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level_2_label',
            field=models.CharField(blank=True, default='Activity', max_length=255, verbose_name='Project/Program Organization Level 2 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_3_label',
            field=models.CharField(blank=True, default='Task', max_length=255, verbose_name='Project/Program Organization Level 3 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_4_label',
            field=models.CharField(blank=True, default='Component', max_length=255, verbose_name='Project/Program Organization Level 4 label'),
        ),
    ]
