# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_auto_20170918_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='country',
            field=models.ManyToManyField(blank=True, to='workflow.Country'),
        ),
    ]
