# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0043_auto_20170918_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_uuid',
            field=models.CharField(default='', max_length=255, verbose_name='Organization UUID'),
        ),
        migrations.AddField(
            model_name='tolauser',
            name='tola_user_uuid',
            field=models.CharField(default='', max_length=255, verbose_name='TolaUser UUID'),
        )
    ]
