# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_auto_20170919_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Sector')),
                ('sector_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_related', to='workflow.Sector')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_nearest',
            field=models.ManyToManyField(related_name='nearest', through='workflow.SectorRelated', to='workflow.Sector'),
        ),
    ]
