# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0045_auto_20170920_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorrelated',
            name='org_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectorrelated',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization'),
        ),
    ]
