# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0046_auto_20170920_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='TolaData', max_length=255, verbose_name='Industry Name')),
                ('description', models.TextField(blank=True, max_length=765, null=True, verbose_name='Description/Notes')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='org_sector', to='workflow.Sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org_specific_sector', to='workflow.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.ManyToManyField(blank=True, to='workflow.Industry'),
        ),
    ]
