# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0047_auto_20170920_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorrelated',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
