# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0048_auto_20170920_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLevel1Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('sector', models.ManyToManyField(blank=True, related_name='level1_primary_sector', to='workflow.Sector')),
                ('sub_sector', models.ManyToManyField(blank=True, related_name='level1_sub_sector', to='workflow.Sector')),
                ('workflowlevel1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_sectors', to='workflow.WorkflowLevel1')),
            ],
            options={
                'ordering': ('workflowlevel1',),
                'verbose_name_plural': 'WorkflowLevel1 Sectors',
            },
        ),
    ]
