# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0049_workflowlevel1sectors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowlevel1sectors',
            options={'ordering': ('create_date',), 'verbose_name_plural': 'WorkflowLevel1 Sectors'},
        ),
    ]
