# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0050_auto_20170921_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlevel1sectors',
            name='sector',
        ),
        migrations.AddField(
            model_name='workflowlevel1sectors',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level1_primary_sector', to='workflow.Sector'),
        ),
    ]
