# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0051_auto_20170921_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkflowLevel1Sectors',
            new_name='WorkflowLevel1Sector',
        ),
    ]
