# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0052_auto_20170921_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlevel1',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowlevel1',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
