# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0053_organization_organization_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Organization UUID'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='tola_user_uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='TolaUser UUID'),
        ),
    ]
