# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0054_auto_20170921_0327'),
        ('workflow', '0053_auto_20170921_0641'),
    ]

    operations = [
    ]
