# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0059_auto_20170927_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkflowlevel2',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
