# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0059_auto_20170927_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='milestone_date',
            new_name='milestone_end_date',
        ),
        migrations.AddField(
            model_name='milestone',
            name='milestone_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
