# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 10:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0060_auto_20171003_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowlevel2sort',
            options={'ordering': ('workflowlevel1', 'workflowlevel2_id'), 'verbose_name_plural': 'WorkflowLevel Sort'},
        ),
        migrations.RemoveField(
            model_name='workflowlevel2sort',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='workflowlevel2sort',
            name='sort_array',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
