# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0061_auto_20171004_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowteam',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
